# Generated by Django 5.2.10 on 2026-01-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.price')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_links', to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.reservation')),
            ],
            options={
                'db_table': 'reservations_representation_reservation',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_must_be_positive')],
            },
        ),
    ]
