# Generated by Django 5.2.10 on 2026-02-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.price')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.reservation')),
            ],
            options={
                'db_table': 'representation_reservation',
            },
        ),
        migrations.CreateModel(
            name='RepresentationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_prices', to='catalogue.price')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_prices', to='catalogue.representation')),
            ],
            options={
                'db_table': 'representation_price',
                'unique_together': {('representation', 'price')},
            },
        ),
    ]
